### ISSUE TITLE
make friend

### ISSUE THREAD

**Issue by XingZhiKe** [White-White/mocha#4]
你好，给你发过一封邮件，能查收并回复一下吗

**Comment by White-White** [comment]
Hi 我的邮箱是 jinhao.zhang@icloud.com，我查看了下没有新邮件
麻烦再重发一下吧

**Comment by XingZhiKe** [comment]
你好，我邮件发了，能收到吗？
我最近也在研究macho文件，主要是基于machoview的源码。目前基本了解是怎么解析macho文件了。
但是有许多问题，尚不明白，看到你这里也在研究这个，希望能和你加个好友，多交流一下，我的微信是:ontheway_wwj。

**Comment by XingZhiKe** [comment]
我也在看《程序员的自我修养—链接、装载与库》，遇到一些问题，希望能多交流
1、strings、otool、nm和machoview获取获取的信息不太相同，不知道差异在何处
2、基于macho文件的研究，能有哪些实际应用（目前也想到一些场景，但是不多）
这个要研究透彻，估计还要看objc4、dyld3的源码，才能整个流程比较了解

**Comment by White-White** [comment]
mocha工程里的swift源码比较清晰，可以对照着这几个开源库的源码研究下

发自我的iPhone
